//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.25 at 08:19:28 pm IST 
//


package com.address.soap.api.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AddressRangeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AddressRangeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Street" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="StreetSide" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HousenumberForm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HouseNumberAdditionForm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HousenumberUntil" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Postcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SubCity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="District" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddressRangeType", propOrder = {
    "street",
    "streetSide",
    "housenumberForm",
    "houseNumberAdditionForm",
    "housenumberUntil",
    "postcode",
    "city",
    "subCity",
    "district"
})
public class AddressRangeType {

    @XmlElement(name = "Street", required = true)
    protected String street;
    @XmlElement(name = "StreetSide", required = true)
    protected String streetSide;
    @XmlElement(name = "HousenumberForm", required = true)
    protected String housenumberForm;
    @XmlElement(name = "HouseNumberAdditionForm", required = true)
    protected String houseNumberAdditionForm;
    @XmlElement(name = "HousenumberUntil", required = true)
    protected String housenumberUntil;
    @XmlElement(name = "Postcode", required = true)
    protected String postcode;
    @XmlElement(name = "City", required = true)
    protected String city;
    @XmlElement(name = "SubCity", required = true)
    protected String subCity;
    @XmlElement(name = "District", required = true)
    protected String district;

    /**
     * Gets the value of the street property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreet() {
        return street;
    }

    /**
     * Sets the value of the street property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreet(String value) {
        this.street = value;
    }

    /**
     * Gets the value of the streetSide property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetSide() {
        return streetSide;
    }

    /**
     * Sets the value of the streetSide property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetSide(String value) {
        this.streetSide = value;
    }

    /**
     * Gets the value of the housenumberForm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHousenumberForm() {
        return housenumberForm;
    }

    /**
     * Sets the value of the housenumberForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHousenumberForm(String value) {
        this.housenumberForm = value;
    }

    /**
     * Gets the value of the houseNumberAdditionForm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHouseNumberAdditionForm() {
        return houseNumberAdditionForm;
    }

    /**
     * Sets the value of the houseNumberAdditionForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHouseNumberAdditionForm(String value) {
        this.houseNumberAdditionForm = value;
    }

    /**
     * Gets the value of the housenumberUntil property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHousenumberUntil() {
        return housenumberUntil;
    }

    /**
     * Sets the value of the housenumberUntil property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHousenumberUntil(String value) {
        this.housenumberUntil = value;
    }

    /**
     * Gets the value of the postcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * Sets the value of the postcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostcode(String value) {
        this.postcode = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the subCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubCity() {
        return subCity;
    }

    /**
     * Sets the value of the subCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubCity(String value) {
        this.subCity = value;
    }

    /**
     * Gets the value of the district property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDistrict() {
        return district;
    }

    /**
     * Sets the value of the district property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistrict(String value) {
        this.district = value;
    }

}
