//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.25 at 08:19:28 pm IST 
//


package com.address.soap.api.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AviailabilityOptionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AviailabilityOptionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OptionName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AvailabilityIndicator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AvailabilityReason" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RfoDaten" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="PortextentionDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="AdditionalInformation" type="{http://www.api.soap.address.com/model}AdditionalInformationType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AviailabilityOptionType", propOrder = {
    "optionName",
    "availabilityIndicator",
    "availabilityReason",
    "rfoDaten",
    "portextentionDate",
    "additionalInformation"
})
public class AviailabilityOptionType {

    @XmlElement(name = "OptionName", required = true)
    protected String optionName;
    @XmlElement(name = "AvailabilityIndicator", required = true)
    protected String availabilityIndicator;
    @XmlElement(name = "AvailabilityReason", required = true)
    protected String availabilityReason;
    @XmlElement(name = "RfoDaten", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar rfoDaten;
    @XmlElement(name = "PortextentionDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar portextentionDate;
    @XmlElement(name = "AdditionalInformation", required = true)
    protected List<AdditionalInformationType> additionalInformation;

    /**
     * Gets the value of the optionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptionName() {
        return optionName;
    }

    /**
     * Sets the value of the optionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptionName(String value) {
        this.optionName = value;
    }

    /**
     * Gets the value of the availabilityIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvailabilityIndicator() {
        return availabilityIndicator;
    }

    /**
     * Sets the value of the availabilityIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvailabilityIndicator(String value) {
        this.availabilityIndicator = value;
    }

    /**
     * Gets the value of the availabilityReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvailabilityReason() {
        return availabilityReason;
    }

    /**
     * Sets the value of the availabilityReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvailabilityReason(String value) {
        this.availabilityReason = value;
    }

    /**
     * Gets the value of the rfoDaten property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRfoDaten() {
        return rfoDaten;
    }

    /**
     * Sets the value of the rfoDaten property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRfoDaten(XMLGregorianCalendar value) {
        this.rfoDaten = value;
    }

    /**
     * Gets the value of the portextentionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPortextentionDate() {
        return portextentionDate;
    }

    /**
     * Sets the value of the portextentionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPortextentionDate(XMLGregorianCalendar value) {
        this.portextentionDate = value;
    }

    /**
     * Gets the value of the additionalInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdditionalInformationType }
     * 
     * 
     */
    public List<AdditionalInformationType> getAdditionalInformation() {
        if (additionalInformation == null) {
            additionalInformation = new ArrayList<AdditionalInformationType>();
        }
        return this.additionalInformation;
    }

}
