//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.25 at 08:19:28 pm IST 
//


package com.address.soap.api.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AvilabilityInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AvilabilityInformationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AvailabilityDetails" type="{http://www.api.soap.address.com/model}AvailabilityDetailsType"/>
 *         &lt;element name="VoipAvailability" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AreaCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Asb" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HvtInformation" type="{http://www.api.soap.address.com/model}HvtInformationType"/>
 *         &lt;element name="AddressRange" type="{http://www.api.soap.address.com/model}AddressRangeType"/>
 *         &lt;element name="KvzInformation" type="{http://www.api.soap.address.com/model}KvzInformationType"/>
 *         &lt;element name="MfgInformation" type="{http://www.api.soap.address.com/model}MfgInformationType"/>
 *         &lt;element name="AdditionalInformation" type="{http://www.api.soap.address.com/model}AdditionalInformationType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AvilabilityInformationType", propOrder = {
    "availabilityDetails",
    "voipAvailability",
    "areaCode",
    "asb",
    "hvtInformation",
    "addressRange",
    "kvzInformation",
    "mfgInformation",
    "additionalInformation"
})
public class AvilabilityInformationType {

    @XmlElement(name = "AvailabilityDetails", required = true)
    protected AvailabilityDetailsType availabilityDetails;
    @XmlElement(name = "VoipAvailability", required = true)
    protected String voipAvailability;
    @XmlElement(name = "AreaCode", required = true)
    protected String areaCode;
    @XmlElement(name = "Asb", required = true)
    protected String asb;
    @XmlElement(name = "HvtInformation", required = true)
    protected HvtInformationType hvtInformation;
    @XmlElement(name = "AddressRange", required = true)
    protected AddressRangeType addressRange;
    @XmlElement(name = "KvzInformation", required = true)
    protected KvzInformationType kvzInformation;
    @XmlElement(name = "MfgInformation", required = true)
    protected MfgInformationType mfgInformation;
    @XmlElement(name = "AdditionalInformation", required = true)
    protected List<AdditionalInformationType> additionalInformation;

    /**
     * Gets the value of the availabilityDetails property.
     * 
     * @return
     *     possible object is
     *     {@link AvailabilityDetailsType }
     *     
     */
    public AvailabilityDetailsType getAvailabilityDetails() {
        return availabilityDetails;
    }

    /**
     * Sets the value of the availabilityDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link AvailabilityDetailsType }
     *     
     */
    public void setAvailabilityDetails(AvailabilityDetailsType value) {
        this.availabilityDetails = value;
    }

    /**
     * Gets the value of the voipAvailability property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoipAvailability() {
        return voipAvailability;
    }

    /**
     * Sets the value of the voipAvailability property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoipAvailability(String value) {
        this.voipAvailability = value;
    }

    /**
     * Gets the value of the areaCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * Sets the value of the areaCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAreaCode(String value) {
        this.areaCode = value;
    }

    /**
     * Gets the value of the asb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAsb() {
        return asb;
    }

    /**
     * Sets the value of the asb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAsb(String value) {
        this.asb = value;
    }

    /**
     * Gets the value of the hvtInformation property.
     * 
     * @return
     *     possible object is
     *     {@link HvtInformationType }
     *     
     */
    public HvtInformationType getHvtInformation() {
        return hvtInformation;
    }

    /**
     * Sets the value of the hvtInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link HvtInformationType }
     *     
     */
    public void setHvtInformation(HvtInformationType value) {
        this.hvtInformation = value;
    }

    /**
     * Gets the value of the addressRange property.
     * 
     * @return
     *     possible object is
     *     {@link AddressRangeType }
     *     
     */
    public AddressRangeType getAddressRange() {
        return addressRange;
    }

    /**
     * Sets the value of the addressRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressRangeType }
     *     
     */
    public void setAddressRange(AddressRangeType value) {
        this.addressRange = value;
    }

    /**
     * Gets the value of the kvzInformation property.
     * 
     * @return
     *     possible object is
     *     {@link KvzInformationType }
     *     
     */
    public KvzInformationType getKvzInformation() {
        return kvzInformation;
    }

    /**
     * Sets the value of the kvzInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link KvzInformationType }
     *     
     */
    public void setKvzInformation(KvzInformationType value) {
        this.kvzInformation = value;
    }

    /**
     * Gets the value of the mfgInformation property.
     * 
     * @return
     *     possible object is
     *     {@link MfgInformationType }
     *     
     */
    public MfgInformationType getMfgInformation() {
        return mfgInformation;
    }

    /**
     * Sets the value of the mfgInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link MfgInformationType }
     *     
     */
    public void setMfgInformation(MfgInformationType value) {
        this.mfgInformation = value;
    }

    /**
     * Gets the value of the additionalInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdditionalInformationType }
     * 
     * 
     */
    public List<AdditionalInformationType> getAdditionalInformation() {
        if (additionalInformation == null) {
            additionalInformation = new ArrayList<AdditionalInformationType>();
        }
        return this.additionalInformation;
    }

}
