//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.25 at 08:19:28 pm IST 
//


package com.address.soap.api.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BuildingInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BuildingInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ObjectCategory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ObjectCategoryPresentationTxt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MaxUnits" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="SoldUnits" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="FreeUnits" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="NdpState" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NdpStatePresentationText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ObjectType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NvType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ContractType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Flags" type="{http://www.api.soap.address.com/model}FlagType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BuildingInfoType", propOrder = {
    "objectCategory",
    "objectCategoryPresentationTxt",
    "maxUnits",
    "soldUnits",
    "freeUnits",
    "ndpState",
    "ndpStatePresentationText",
    "objectType",
    "nvType",
    "contractType",
    "flags"
})
public class BuildingInfoType {

    @XmlElement(name = "ObjectCategory", required = true)
    protected String objectCategory;
    @XmlElement(name = "ObjectCategoryPresentationTxt", required = true)
    protected String objectCategoryPresentationTxt;
    @XmlElement(name = "MaxUnits", required = true)
    protected BigInteger maxUnits;
    @XmlElement(name = "SoldUnits", required = true)
    protected BigInteger soldUnits;
    @XmlElement(name = "FreeUnits", required = true)
    protected BigInteger freeUnits;
    @XmlElement(name = "NdpState", required = true)
    protected String ndpState;
    @XmlElement(name = "NdpStatePresentationText", required = true)
    protected String ndpStatePresentationText;
    @XmlElement(name = "ObjectType", required = true)
    protected String objectType;
    @XmlElement(name = "NvType", required = true)
    protected String nvType;
    @XmlElement(name = "ContractType", required = true)
    protected String contractType;
    @XmlElement(name = "Flags", required = true)
    protected FlagType flags;

    /**
     * Gets the value of the objectCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectCategory() {
        return objectCategory;
    }

    /**
     * Sets the value of the objectCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectCategory(String value) {
        this.objectCategory = value;
    }

    /**
     * Gets the value of the objectCategoryPresentationTxt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectCategoryPresentationTxt() {
        return objectCategoryPresentationTxt;
    }

    /**
     * Sets the value of the objectCategoryPresentationTxt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectCategoryPresentationTxt(String value) {
        this.objectCategoryPresentationTxt = value;
    }

    /**
     * Gets the value of the maxUnits property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxUnits() {
        return maxUnits;
    }

    /**
     * Sets the value of the maxUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxUnits(BigInteger value) {
        this.maxUnits = value;
    }

    /**
     * Gets the value of the soldUnits property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSoldUnits() {
        return soldUnits;
    }

    /**
     * Sets the value of the soldUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSoldUnits(BigInteger value) {
        this.soldUnits = value;
    }

    /**
     * Gets the value of the freeUnits property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFreeUnits() {
        return freeUnits;
    }

    /**
     * Sets the value of the freeUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFreeUnits(BigInteger value) {
        this.freeUnits = value;
    }

    /**
     * Gets the value of the ndpState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNdpState() {
        return ndpState;
    }

    /**
     * Sets the value of the ndpState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNdpState(String value) {
        this.ndpState = value;
    }

    /**
     * Gets the value of the ndpStatePresentationText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNdpStatePresentationText() {
        return ndpStatePresentationText;
    }

    /**
     * Sets the value of the ndpStatePresentationText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNdpStatePresentationText(String value) {
        this.ndpStatePresentationText = value;
    }

    /**
     * Gets the value of the objectType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectType() {
        return objectType;
    }

    /**
     * Sets the value of the objectType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectType(String value) {
        this.objectType = value;
    }

    /**
     * Gets the value of the nvType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNvType() {
        return nvType;
    }

    /**
     * Sets the value of the nvType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNvType(String value) {
        this.nvType = value;
    }

    /**
     * Gets the value of the contractType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractType() {
        return contractType;
    }

    /**
     * Sets the value of the contractType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractType(String value) {
        this.contractType = value;
    }

    /**
     * Gets the value of the flags property.
     * 
     * @return
     *     possible object is
     *     {@link FlagType }
     *     
     */
    public FlagType getFlags() {
        return flags;
    }

    /**
     * Sets the value of the flags property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlagType }
     *     
     */
    public void setFlags(FlagType value) {
        this.flags = value;
    }

}
