//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.25 at 08:19:28 pm IST 
//


package com.address.soap.api.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetProductAvailabilityOutputDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetProductAvailabilityOutputDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="KDAvailabilityType" type="{http://www.api.soap.address.com/model}KDAvailabilityType"/>
 *         &lt;element name="KDCallStatus" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="FNAvailablity" type="{http://www.api.soap.address.com/model}FNAvailablityType"/>
 *         &lt;element name="FNCallStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SubCity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="District" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Street" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HouseNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HouseNumberAddition" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AreaCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ExistingCustomerTASI" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ExistingCustomerTN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetProductAvailabilityOutputDataType", propOrder = {
    "kdAvailabilityType",
    "kdCallStatus",
    "fnAvailablity",
    "fnCallStatus",
    "subCity",
    "district",
    "street",
    "houseNumber",
    "houseNumberAddition",
    "areaCode",
    "phoneNumber",
    "existingCustomerTASI",
    "existingCustomerTN"
})
public class GetProductAvailabilityOutputDataType {

    @XmlElement(name = "KDAvailabilityType", required = true)
    protected KDAvailabilityType kdAvailabilityType;
    @XmlElement(name = "KDCallStatus")
    protected int kdCallStatus;
    @XmlElement(name = "FNAvailablity", required = true)
    protected FNAvailablityType fnAvailablity;
    @XmlElement(name = "FNCallStatus", required = true)
    protected String fnCallStatus;
    @XmlElement(name = "SubCity", required = true)
    protected String subCity;
    @XmlElement(name = "District", required = true)
    protected String district;
    @XmlElement(name = "Street", required = true)
    protected String street;
    @XmlElement(name = "HouseNumber", required = true)
    protected String houseNumber;
    @XmlElement(name = "HouseNumberAddition", required = true)
    protected String houseNumberAddition;
    @XmlElement(name = "AreaCode", required = true)
    protected String areaCode;
    @XmlElement(name = "PhoneNumber", required = true)
    protected String phoneNumber;
    @XmlElement(name = "ExistingCustomerTASI", required = true)
    protected String existingCustomerTASI;
    @XmlElement(name = "ExistingCustomerTN", required = true)
    protected String existingCustomerTN;

    /**
     * Gets the value of the kdAvailabilityType property.
     * 
     * @return
     *     possible object is
     *     {@link KDAvailabilityType }
     *     
     */
    public KDAvailabilityType getKDAvailabilityType() {
        return kdAvailabilityType;
    }

    /**
     * Sets the value of the kdAvailabilityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link KDAvailabilityType }
     *     
     */
    public void setKDAvailabilityType(KDAvailabilityType value) {
        this.kdAvailabilityType = value;
    }

    /**
     * Gets the value of the kdCallStatus property.
     * 
     */
    public int getKDCallStatus() {
        return kdCallStatus;
    }

    /**
     * Sets the value of the kdCallStatus property.
     * 
     */
    public void setKDCallStatus(int value) {
        this.kdCallStatus = value;
    }

    /**
     * Gets the value of the fnAvailablity property.
     * 
     * @return
     *     possible object is
     *     {@link FNAvailablityType }
     *     
     */
    public FNAvailablityType getFNAvailablity() {
        return fnAvailablity;
    }

    /**
     * Sets the value of the fnAvailablity property.
     * 
     * @param value
     *     allowed object is
     *     {@link FNAvailablityType }
     *     
     */
    public void setFNAvailablity(FNAvailablityType value) {
        this.fnAvailablity = value;
    }

    /**
     * Gets the value of the fnCallStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFNCallStatus() {
        return fnCallStatus;
    }

    /**
     * Sets the value of the fnCallStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFNCallStatus(String value) {
        this.fnCallStatus = value;
    }

    /**
     * Gets the value of the subCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubCity() {
        return subCity;
    }

    /**
     * Sets the value of the subCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubCity(String value) {
        this.subCity = value;
    }

    /**
     * Gets the value of the district property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDistrict() {
        return district;
    }

    /**
     * Sets the value of the district property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistrict(String value) {
        this.district = value;
    }

    /**
     * Gets the value of the street property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreet() {
        return street;
    }

    /**
     * Sets the value of the street property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreet(String value) {
        this.street = value;
    }

    /**
     * Gets the value of the houseNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHouseNumber() {
        return houseNumber;
    }

    /**
     * Sets the value of the houseNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHouseNumber(String value) {
        this.houseNumber = value;
    }

    /**
     * Gets the value of the houseNumberAddition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHouseNumberAddition() {
        return houseNumberAddition;
    }

    /**
     * Sets the value of the houseNumberAddition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHouseNumberAddition(String value) {
        this.houseNumberAddition = value;
    }

    /**
     * Gets the value of the areaCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * Sets the value of the areaCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAreaCode(String value) {
        this.areaCode = value;
    }

    /**
     * Gets the value of the phoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * Sets the value of the phoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneNumber(String value) {
        this.phoneNumber = value;
    }

    /**
     * Gets the value of the existingCustomerTASI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExistingCustomerTASI() {
        return existingCustomerTASI;
    }

    /**
     * Sets the value of the existingCustomerTASI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExistingCustomerTASI(String value) {
        this.existingCustomerTASI = value;
    }

    /**
     * Gets the value of the existingCustomerTN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExistingCustomerTN() {
        return existingCustomerTN;
    }

    /**
     * Sets the value of the existingCustomerTN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExistingCustomerTN(String value) {
        this.existingCustomerTN = value;
    }

}
