//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.25 at 08:19:28 pm IST 
//


package com.address.soap.api.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Event" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Data" type="{http://www.api.soap.address.com/model}GetProductAvailabilityOutputDataType"/>
 *         &lt;element name="Statue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "event",
    "data",
    "statue"
})
@XmlRootElement(name = "GetProductAvailabilityOutputType")
public class GetProductAvailabilityOutputType {

    @XmlElement(name = "Event", required = true)
    protected String event;
    @XmlElement(name = "Data", required = true)
    protected GetProductAvailabilityOutputDataType data;
    @XmlElement(name = "Statue", required = true)
    protected String statue;

    /**
     * Gets the value of the event property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEvent() {
        return event;
    }

    /**
     * Sets the value of the event property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEvent(String value) {
        this.event = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link GetProductAvailabilityOutputDataType }
     *     
     */
    public GetProductAvailabilityOutputDataType getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetProductAvailabilityOutputDataType }
     *     
     */
    public void setData(GetProductAvailabilityOutputDataType value) {
        this.data = value;
    }

    /**
     * Gets the value of the statue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatue() {
        return statue;
    }

    /**
     * Sets the value of the statue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatue(String value) {
        this.statue = value;
    }

}
