//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.25 at 08:19:28 pm IST 
//


package com.address.soap.api.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HvtInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HvtInformationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CableType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HvtTnb" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HvtRegion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HvtPostCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HvtCity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HvtStreet" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AdditionalInformation" type="{http://www.api.soap.address.com/model}AdditionalInformationType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HvtInformationType", propOrder = {
    "cableType",
    "hvtTnb",
    "hvtRegion",
    "hvtPostCode",
    "hvtCity",
    "hvtStreet",
    "additionalInformation"
})
public class HvtInformationType {

    @XmlElement(name = "CableType", required = true)
    protected String cableType;
    @XmlElement(name = "HvtTnb", required = true)
    protected String hvtTnb;
    @XmlElement(name = "HvtRegion", required = true)
    protected String hvtRegion;
    @XmlElement(name = "HvtPostCode", required = true)
    protected String hvtPostCode;
    @XmlElement(name = "HvtCity", required = true)
    protected String hvtCity;
    @XmlElement(name = "HvtStreet", required = true)
    protected String hvtStreet;
    @XmlElement(name = "AdditionalInformation", required = true)
    protected List<AdditionalInformationType> additionalInformation;

    /**
     * Gets the value of the cableType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCableType() {
        return cableType;
    }

    /**
     * Sets the value of the cableType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCableType(String value) {
        this.cableType = value;
    }

    /**
     * Gets the value of the hvtTnb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHvtTnb() {
        return hvtTnb;
    }

    /**
     * Sets the value of the hvtTnb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHvtTnb(String value) {
        this.hvtTnb = value;
    }

    /**
     * Gets the value of the hvtRegion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHvtRegion() {
        return hvtRegion;
    }

    /**
     * Sets the value of the hvtRegion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHvtRegion(String value) {
        this.hvtRegion = value;
    }

    /**
     * Gets the value of the hvtPostCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHvtPostCode() {
        return hvtPostCode;
    }

    /**
     * Sets the value of the hvtPostCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHvtPostCode(String value) {
        this.hvtPostCode = value;
    }

    /**
     * Gets the value of the hvtCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHvtCity() {
        return hvtCity;
    }

    /**
     * Sets the value of the hvtCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHvtCity(String value) {
        this.hvtCity = value;
    }

    /**
     * Gets the value of the hvtStreet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHvtStreet() {
        return hvtStreet;
    }

    /**
     * Sets the value of the hvtStreet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHvtStreet(String value) {
        this.hvtStreet = value;
    }

    /**
     * Gets the value of the additionalInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdditionalInformationType }
     * 
     * 
     */
    public List<AdditionalInformationType> getAdditionalInformation() {
        if (additionalInformation == null) {
            additionalInformation = new ArrayList<AdditionalInformationType>();
        }
        return this.additionalInformation;
    }

}
