//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.25 at 08:19:28 pm IST 
//


package com.address.soap.api.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for KDAvailabilityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KDAvailabilityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ServiceCategoryInfo" type="{http://www.api.soap.address.com/model}ServiceCategoryUInfoType" maxOccurs="unbounded"/>
 *         &lt;element name="objectTags" type="{http://www.api.soap.address.com/model}ObjectTagType" maxOccurs="unbounded"/>
 *         &lt;element name="Buildingifo" type="{http://www.api.soap.address.com/model}BuildingInfoType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KDAvailabilityType", propOrder = {
    "serviceCategoryInfo",
    "objectTags",
    "buildingifo"
})
public class KDAvailabilityType {

    @XmlElement(name = "ServiceCategoryInfo", required = true)
    protected List<ServiceCategoryUInfoType> serviceCategoryInfo;
    @XmlElement(required = true)
    protected List<ObjectTagType> objectTags;
    @XmlElement(name = "Buildingifo", required = true)
    protected BuildingInfoType buildingifo;

    /**
     * Gets the value of the serviceCategoryInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the serviceCategoryInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getServiceCategoryInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ServiceCategoryUInfoType }
     * 
     * 
     */
    public List<ServiceCategoryUInfoType> getServiceCategoryInfo() {
        if (serviceCategoryInfo == null) {
            serviceCategoryInfo = new ArrayList<ServiceCategoryUInfoType>();
        }
        return this.serviceCategoryInfo;
    }

    /**
     * Gets the value of the objectTags property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the objectTags property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObjectTags().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObjectTagType }
     * 
     * 
     */
    public List<ObjectTagType> getObjectTags() {
        if (objectTags == null) {
            objectTags = new ArrayList<ObjectTagType>();
        }
        return this.objectTags;
    }

    /**
     * Gets the value of the buildingifo property.
     * 
     * @return
     *     possible object is
     *     {@link BuildingInfoType }
     *     
     */
    public BuildingInfoType getBuildingifo() {
        return buildingifo;
    }

    /**
     * Sets the value of the buildingifo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BuildingInfoType }
     *     
     */
    public void setBuildingifo(BuildingInfoType value) {
        this.buildingifo = value;
    }

}
