//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.25 at 08:19:28 pm IST 
//


package com.address.soap.api.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.address.soap.api.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.address.soap.api.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link KvzInformationType }
     * 
     */
    public KvzInformationType createKvzInformationType() {
        return new KvzInformationType();
    }

    /**
     * Create an instance of {@link AvilabilityInformationType }
     * 
     */
    public AvilabilityInformationType createAvilabilityInformationType() {
        return new AvilabilityInformationType();
    }

    /**
     * Create an instance of {@link ServiceCategoryUInfoType }
     * 
     */
    public ServiceCategoryUInfoType createServiceCategoryUInfoType() {
        return new ServiceCategoryUInfoType();
    }

    /**
     * Create an instance of {@link KDAvailabilityType }
     * 
     */
    public KDAvailabilityType createKDAvailabilityType() {
        return new KDAvailabilityType();
    }

    /**
     * Create an instance of {@link AdditionalInformationType }
     * 
     */
    public AdditionalInformationType createAdditionalInformationType() {
        return new AdditionalInformationType();
    }

    /**
     * Create an instance of {@link BuildingInfoType }
     * 
     */
    public BuildingInfoType createBuildingInfoType() {
        return new BuildingInfoType();
    }

    /**
     * Create an instance of {@link AviailabilityOptionType }
     * 
     */
    public AviailabilityOptionType createAviailabilityOptionType() {
        return new AviailabilityOptionType();
    }

    /**
     * Create an instance of {@link AvailabilityDetailsType }
     * 
     */
    public AvailabilityDetailsType createAvailabilityDetailsType() {
        return new AvailabilityDetailsType();
    }

    /**
     * Create an instance of {@link FlagType }
     * 
     */
    public FlagType createFlagType() {
        return new FlagType();
    }

    /**
     * Create an instance of {@link AddressRangeType }
     * 
     */
    public AddressRangeType createAddressRangeType() {
        return new AddressRangeType();
    }

    /**
     * Create an instance of {@link AvailabilityDetailType }
     * 
     */
    public AvailabilityDetailType createAvailabilityDetailType() {
        return new AvailabilityDetailType();
    }

    /**
     * Create an instance of {@link GetProductAvailabilityInputType }
     * 
     */
    public GetProductAvailabilityInputType createGetProductAvailabilityInputType() {
        return new GetProductAvailabilityInputType();
    }

    /**
     * Create an instance of {@link ObjectTagType }
     * 
     */
    public ObjectTagType createObjectTagType() {
        return new ObjectTagType();
    }

    /**
     * Create an instance of {@link GetProductAvailabilityOutputType }
     * 
     */
    public GetProductAvailabilityOutputType createGetProductAvailabilityOutputType() {
        return new GetProductAvailabilityOutputType();
    }

    /**
     * Create an instance of {@link HvtInformationType }
     * 
     */
    public HvtInformationType createHvtInformationType() {
        return new HvtInformationType();
    }

    /**
     * Create an instance of {@link GetProductAvailabilityOutputDataType }
     * 
     */
    public GetProductAvailabilityOutputDataType createGetProductAvailabilityOutputDataType() {
        return new GetProductAvailabilityOutputDataType();
    }

    /**
     * Create an instance of {@link MfgInformationType }
     * 
     */
    public MfgInformationType createMfgInformationType() {
        return new MfgInformationType();
    }

    /**
     * Create an instance of {@link FNAvailablityType }
     * 
     */
    public FNAvailablityType createFNAvailablityType() {
        return new FNAvailablityType();
    }

    /**
     * Create an instance of {@link GetProductAvailabilityInputDataType }
     * 
     */
    public GetProductAvailabilityInputDataType createGetProductAvailabilityInputDataType() {
        return new GetProductAvailabilityInputDataType();
    }

}
