//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.25 at 08:19:28 pm IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.api.soap.address.com/model", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.address.soap.api.model;
